/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSpamSecurityIndexRouteImport } from './routes/_authenticated/spam-security/index'
import { Route as AuthenticatedServersIndexRouteImport } from './routes/_authenticated/servers/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedLogsIndexRouteImport } from './routes/_authenticated/logs/index'
import { Route as AuthenticatedIpReputationIndexRouteImport } from './routes/_authenticated/ip-reputation/index'
import { Route as AuthenticatedEmailFlowIndexRouteImport } from './routes/_authenticated/email-flow/index'
import { Route as AuthenticatedDomainsIndexRouteImport } from './routes/_authenticated/domains/index'
import { Route as AuthenticatedDestinationsIndexRouteImport } from './routes/_authenticated/destinations/index'
import { Route as AuthenticatedAlertsIndexRouteImport } from './routes/_authenticated/alerts/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedUsersAddressRouteImport } from './routes/_authenticated/users/$address'
import { Route as AuthenticatedSpamSecurityTlsRouteImport } from './routes/_authenticated/spam-security/tls'
import { Route as AuthenticatedSpamSecurityAuthenticationRouteImport } from './routes/_authenticated/spam-security/authentication'
import { Route as AuthenticatedServersHeatmapRouteImport } from './routes/_authenticated/servers/heatmap'
import { Route as AuthenticatedServersComparisonRouteImport } from './routes/_authenticated/servers/comparison'
import { Route as AuthenticatedServersNodeIdRouteImport } from './routes/_authenticated/servers/$nodeId'
import { Route as AuthenticatedIpReputationIpRouteImport } from './routes/_authenticated/ip-reputation/$ip'
import { Route as AuthenticatedEmailFlowQueueRouteImport } from './routes/_authenticated/email-flow/queue'
import { Route as AuthenticatedEmailFlowPerformanceRouteImport } from './routes/_authenticated/email-flow/performance'
import { Route as AuthenticatedDomainsDomainRouteImport } from './routes/_authenticated/domains/$domain'
import { Route as AuthenticatedDestinationsDomainRouteImport } from './routes/_authenticated/destinations/$domain'
import { Route as AuthenticatedAlertsRulesRouteImport } from './routes/_authenticated/alerts/rules'
import { Route as AuthenticatedAlertsHistoryRouteImport } from './routes/_authenticated/alerts/history'
import { Route as AuthenticatedAlertsChannelsRouteImport } from './routes/_authenticated/alerts/channels'
import { Route as AuthenticatedServersZonemtaIndexRouteImport } from './routes/_authenticated/servers/zonemta/index'
import { Route as AuthenticatedServersZonemtaNodeIdRouteImport } from './routes/_authenticated/servers/zonemta/$nodeId'
import { Route as AuthenticatedLogsTraceMessageIdRouteImport } from './routes/_authenticated/logs/trace.$messageId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpamSecurityIndexRoute =
  AuthenticatedSpamSecurityIndexRouteImport.update({
    id: '/spam-security/',
    path: '/spam-security/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServersIndexRoute =
  AuthenticatedServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogsIndexRoute = AuthenticatedLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIpReputationIndexRoute =
  AuthenticatedIpReputationIndexRouteImport.update({
    id: '/ip-reputation/',
    path: '/ip-reputation/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmailFlowIndexRoute =
  AuthenticatedEmailFlowIndexRouteImport.update({
    id: '/email-flow/',
    path: '/email-flow/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDomainsIndexRoute =
  AuthenticatedDomainsIndexRouteImport.update({
    id: '/domains/',
    path: '/domains/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDestinationsIndexRoute =
  AuthenticatedDestinationsIndexRouteImport.update({
    id: '/destinations/',
    path: '/destinations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlertsIndexRoute =
  AuthenticatedAlertsIndexRouteImport.update({
    id: '/alerts/',
    path: '/alerts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersAddressRoute =
  AuthenticatedUsersAddressRouteImport.update({
    id: '/users/$address',
    path: '/users/$address',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpamSecurityTlsRoute =
  AuthenticatedSpamSecurityTlsRouteImport.update({
    id: '/spam-security/tls',
    path: '/spam-security/tls',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpamSecurityAuthenticationRoute =
  AuthenticatedSpamSecurityAuthenticationRouteImport.update({
    id: '/spam-security/authentication',
    path: '/spam-security/authentication',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServersHeatmapRoute =
  AuthenticatedServersHeatmapRouteImport.update({
    id: '/servers/heatmap',
    path: '/servers/heatmap',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServersComparisonRoute =
  AuthenticatedServersComparisonRouteImport.update({
    id: '/servers/comparison',
    path: '/servers/comparison',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServersNodeIdRoute =
  AuthenticatedServersNodeIdRouteImport.update({
    id: '/servers/$nodeId',
    path: '/servers/$nodeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIpReputationIpRoute =
  AuthenticatedIpReputationIpRouteImport.update({
    id: '/ip-reputation/$ip',
    path: '/ip-reputation/$ip',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmailFlowQueueRoute =
  AuthenticatedEmailFlowQueueRouteImport.update({
    id: '/email-flow/queue',
    path: '/email-flow/queue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmailFlowPerformanceRoute =
  AuthenticatedEmailFlowPerformanceRouteImport.update({
    id: '/email-flow/performance',
    path: '/email-flow/performance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDomainsDomainRoute =
  AuthenticatedDomainsDomainRouteImport.update({
    id: '/domains/$domain',
    path: '/domains/$domain',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDestinationsDomainRoute =
  AuthenticatedDestinationsDomainRouteImport.update({
    id: '/destinations/$domain',
    path: '/destinations/$domain',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlertsRulesRoute =
  AuthenticatedAlertsRulesRouteImport.update({
    id: '/alerts/rules',
    path: '/alerts/rules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlertsHistoryRoute =
  AuthenticatedAlertsHistoryRouteImport.update({
    id: '/alerts/history',
    path: '/alerts/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlertsChannelsRoute =
  AuthenticatedAlertsChannelsRouteImport.update({
    id: '/alerts/channels',
    path: '/alerts/channels',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServersZonemtaIndexRoute =
  AuthenticatedServersZonemtaIndexRouteImport.update({
    id: '/servers/zonemta/',
    path: '/servers/zonemta/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServersZonemtaNodeIdRoute =
  AuthenticatedServersZonemtaNodeIdRouteImport.update({
    id: '/servers/zonemta/$nodeId',
    path: '/servers/zonemta/$nodeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogsTraceMessageIdRoute =
  AuthenticatedLogsTraceMessageIdRouteImport.update({
    id: '/logs/trace/$messageId',
    path: '/logs/trace/$messageId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/alerts/channels': typeof AuthenticatedAlertsChannelsRoute
  '/alerts/history': typeof AuthenticatedAlertsHistoryRoute
  '/alerts/rules': typeof AuthenticatedAlertsRulesRoute
  '/destinations/$domain': typeof AuthenticatedDestinationsDomainRoute
  '/domains/$domain': typeof AuthenticatedDomainsDomainRoute
  '/email-flow/performance': typeof AuthenticatedEmailFlowPerformanceRoute
  '/email-flow/queue': typeof AuthenticatedEmailFlowQueueRoute
  '/ip-reputation/$ip': typeof AuthenticatedIpReputationIpRoute
  '/servers/$nodeId': typeof AuthenticatedServersNodeIdRoute
  '/servers/comparison': typeof AuthenticatedServersComparisonRoute
  '/servers/heatmap': typeof AuthenticatedServersHeatmapRoute
  '/spam-security/authentication': typeof AuthenticatedSpamSecurityAuthenticationRoute
  '/spam-security/tls': typeof AuthenticatedSpamSecurityTlsRoute
  '/users/$address': typeof AuthenticatedUsersAddressRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/destinations/': typeof AuthenticatedDestinationsIndexRoute
  '/domains/': typeof AuthenticatedDomainsIndexRoute
  '/email-flow/': typeof AuthenticatedEmailFlowIndexRoute
  '/ip-reputation/': typeof AuthenticatedIpReputationIndexRoute
  '/logs/': typeof AuthenticatedLogsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/servers/': typeof AuthenticatedServersIndexRoute
  '/spam-security/': typeof AuthenticatedSpamSecurityIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/logs/trace/$messageId': typeof AuthenticatedLogsTraceMessageIdRoute
  '/servers/zonemta/$nodeId': typeof AuthenticatedServersZonemtaNodeIdRoute
  '/servers/zonemta/': typeof AuthenticatedServersZonemtaIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/alerts/channels': typeof AuthenticatedAlertsChannelsRoute
  '/alerts/history': typeof AuthenticatedAlertsHistoryRoute
  '/alerts/rules': typeof AuthenticatedAlertsRulesRoute
  '/destinations/$domain': typeof AuthenticatedDestinationsDomainRoute
  '/domains/$domain': typeof AuthenticatedDomainsDomainRoute
  '/email-flow/performance': typeof AuthenticatedEmailFlowPerformanceRoute
  '/email-flow/queue': typeof AuthenticatedEmailFlowQueueRoute
  '/ip-reputation/$ip': typeof AuthenticatedIpReputationIpRoute
  '/servers/$nodeId': typeof AuthenticatedServersNodeIdRoute
  '/servers/comparison': typeof AuthenticatedServersComparisonRoute
  '/servers/heatmap': typeof AuthenticatedServersHeatmapRoute
  '/spam-security/authentication': typeof AuthenticatedSpamSecurityAuthenticationRoute
  '/spam-security/tls': typeof AuthenticatedSpamSecurityTlsRoute
  '/users/$address': typeof AuthenticatedUsersAddressRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/alerts': typeof AuthenticatedAlertsIndexRoute
  '/destinations': typeof AuthenticatedDestinationsIndexRoute
  '/domains': typeof AuthenticatedDomainsIndexRoute
  '/email-flow': typeof AuthenticatedEmailFlowIndexRoute
  '/ip-reputation': typeof AuthenticatedIpReputationIndexRoute
  '/logs': typeof AuthenticatedLogsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/servers': typeof AuthenticatedServersIndexRoute
  '/spam-security': typeof AuthenticatedSpamSecurityIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/logs/trace/$messageId': typeof AuthenticatedLogsTraceMessageIdRoute
  '/servers/zonemta/$nodeId': typeof AuthenticatedServersZonemtaNodeIdRoute
  '/servers/zonemta': typeof AuthenticatedServersZonemtaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/alerts/channels': typeof AuthenticatedAlertsChannelsRoute
  '/_authenticated/alerts/history': typeof AuthenticatedAlertsHistoryRoute
  '/_authenticated/alerts/rules': typeof AuthenticatedAlertsRulesRoute
  '/_authenticated/destinations/$domain': typeof AuthenticatedDestinationsDomainRoute
  '/_authenticated/domains/$domain': typeof AuthenticatedDomainsDomainRoute
  '/_authenticated/email-flow/performance': typeof AuthenticatedEmailFlowPerformanceRoute
  '/_authenticated/email-flow/queue': typeof AuthenticatedEmailFlowQueueRoute
  '/_authenticated/ip-reputation/$ip': typeof AuthenticatedIpReputationIpRoute
  '/_authenticated/servers/$nodeId': typeof AuthenticatedServersNodeIdRoute
  '/_authenticated/servers/comparison': typeof AuthenticatedServersComparisonRoute
  '/_authenticated/servers/heatmap': typeof AuthenticatedServersHeatmapRoute
  '/_authenticated/spam-security/authentication': typeof AuthenticatedSpamSecurityAuthenticationRoute
  '/_authenticated/spam-security/tls': typeof AuthenticatedSpamSecurityTlsRoute
  '/_authenticated/users/$address': typeof AuthenticatedUsersAddressRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/_authenticated/destinations/': typeof AuthenticatedDestinationsIndexRoute
  '/_authenticated/domains/': typeof AuthenticatedDomainsIndexRoute
  '/_authenticated/email-flow/': typeof AuthenticatedEmailFlowIndexRoute
  '/_authenticated/ip-reputation/': typeof AuthenticatedIpReputationIndexRoute
  '/_authenticated/logs/': typeof AuthenticatedLogsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/servers/': typeof AuthenticatedServersIndexRoute
  '/_authenticated/spam-security/': typeof AuthenticatedSpamSecurityIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/logs/trace/$messageId': typeof AuthenticatedLogsTraceMessageIdRoute
  '/_authenticated/servers/zonemta/$nodeId': typeof AuthenticatedServersZonemtaNodeIdRoute
  '/_authenticated/servers/zonemta/': typeof AuthenticatedServersZonemtaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts/channels'
    | '/alerts/history'
    | '/alerts/rules'
    | '/destinations/$domain'
    | '/domains/$domain'
    | '/email-flow/performance'
    | '/email-flow/queue'
    | '/ip-reputation/$ip'
    | '/servers/$nodeId'
    | '/servers/comparison'
    | '/servers/heatmap'
    | '/spam-security/authentication'
    | '/spam-security/tls'
    | '/users/$address'
    | '/admin/'
    | '/alerts/'
    | '/destinations/'
    | '/domains/'
    | '/email-flow/'
    | '/ip-reputation/'
    | '/logs/'
    | '/reports/'
    | '/servers/'
    | '/spam-security/'
    | '/users/'
    | '/logs/trace/$messageId'
    | '/servers/zonemta/$nodeId'
    | '/servers/zonemta/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/alerts/channels'
    | '/alerts/history'
    | '/alerts/rules'
    | '/destinations/$domain'
    | '/domains/$domain'
    | '/email-flow/performance'
    | '/email-flow/queue'
    | '/ip-reputation/$ip'
    | '/servers/$nodeId'
    | '/servers/comparison'
    | '/servers/heatmap'
    | '/spam-security/authentication'
    | '/spam-security/tls'
    | '/users/$address'
    | '/admin'
    | '/alerts'
    | '/destinations'
    | '/domains'
    | '/email-flow'
    | '/ip-reputation'
    | '/logs'
    | '/reports'
    | '/servers'
    | '/spam-security'
    | '/users'
    | '/logs/trace/$messageId'
    | '/servers/zonemta/$nodeId'
    | '/servers/zonemta'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/alerts/channels'
    | '/_authenticated/alerts/history'
    | '/_authenticated/alerts/rules'
    | '/_authenticated/destinations/$domain'
    | '/_authenticated/domains/$domain'
    | '/_authenticated/email-flow/performance'
    | '/_authenticated/email-flow/queue'
    | '/_authenticated/ip-reputation/$ip'
    | '/_authenticated/servers/$nodeId'
    | '/_authenticated/servers/comparison'
    | '/_authenticated/servers/heatmap'
    | '/_authenticated/spam-security/authentication'
    | '/_authenticated/spam-security/tls'
    | '/_authenticated/users/$address'
    | '/_authenticated/admin/'
    | '/_authenticated/alerts/'
    | '/_authenticated/destinations/'
    | '/_authenticated/domains/'
    | '/_authenticated/email-flow/'
    | '/_authenticated/ip-reputation/'
    | '/_authenticated/logs/'
    | '/_authenticated/reports/'
    | '/_authenticated/servers/'
    | '/_authenticated/spam-security/'
    | '/_authenticated/users/'
    | '/_authenticated/logs/trace/$messageId'
    | '/_authenticated/servers/zonemta/$nodeId'
    | '/_authenticated/servers/zonemta/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spam-security/': {
      id: '/_authenticated/spam-security/'
      path: '/spam-security'
      fullPath: '/spam-security/'
      preLoaderRoute: typeof AuthenticatedSpamSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/': {
      id: '/_authenticated/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AuthenticatedServersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs/': {
      id: '/_authenticated/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof AuthenticatedLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ip-reputation/': {
      id: '/_authenticated/ip-reputation/'
      path: '/ip-reputation'
      fullPath: '/ip-reputation/'
      preLoaderRoute: typeof AuthenticatedIpReputationIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email-flow/': {
      id: '/_authenticated/email-flow/'
      path: '/email-flow'
      fullPath: '/email-flow/'
      preLoaderRoute: typeof AuthenticatedEmailFlowIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/domains/': {
      id: '/_authenticated/domains/'
      path: '/domains'
      fullPath: '/domains/'
      preLoaderRoute: typeof AuthenticatedDomainsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/destinations/': {
      id: '/_authenticated/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof AuthenticatedDestinationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts/': {
      id: '/_authenticated/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AuthenticatedAlertsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$address': {
      id: '/_authenticated/users/$address'
      path: '/users/$address'
      fullPath: '/users/$address'
      preLoaderRoute: typeof AuthenticatedUsersAddressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spam-security/tls': {
      id: '/_authenticated/spam-security/tls'
      path: '/spam-security/tls'
      fullPath: '/spam-security/tls'
      preLoaderRoute: typeof AuthenticatedSpamSecurityTlsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spam-security/authentication': {
      id: '/_authenticated/spam-security/authentication'
      path: '/spam-security/authentication'
      fullPath: '/spam-security/authentication'
      preLoaderRoute: typeof AuthenticatedSpamSecurityAuthenticationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/heatmap': {
      id: '/_authenticated/servers/heatmap'
      path: '/servers/heatmap'
      fullPath: '/servers/heatmap'
      preLoaderRoute: typeof AuthenticatedServersHeatmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/comparison': {
      id: '/_authenticated/servers/comparison'
      path: '/servers/comparison'
      fullPath: '/servers/comparison'
      preLoaderRoute: typeof AuthenticatedServersComparisonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/$nodeId': {
      id: '/_authenticated/servers/$nodeId'
      path: '/servers/$nodeId'
      fullPath: '/servers/$nodeId'
      preLoaderRoute: typeof AuthenticatedServersNodeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ip-reputation/$ip': {
      id: '/_authenticated/ip-reputation/$ip'
      path: '/ip-reputation/$ip'
      fullPath: '/ip-reputation/$ip'
      preLoaderRoute: typeof AuthenticatedIpReputationIpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email-flow/queue': {
      id: '/_authenticated/email-flow/queue'
      path: '/email-flow/queue'
      fullPath: '/email-flow/queue'
      preLoaderRoute: typeof AuthenticatedEmailFlowQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email-flow/performance': {
      id: '/_authenticated/email-flow/performance'
      path: '/email-flow/performance'
      fullPath: '/email-flow/performance'
      preLoaderRoute: typeof AuthenticatedEmailFlowPerformanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/domains/$domain': {
      id: '/_authenticated/domains/$domain'
      path: '/domains/$domain'
      fullPath: '/domains/$domain'
      preLoaderRoute: typeof AuthenticatedDomainsDomainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/destinations/$domain': {
      id: '/_authenticated/destinations/$domain'
      path: '/destinations/$domain'
      fullPath: '/destinations/$domain'
      preLoaderRoute: typeof AuthenticatedDestinationsDomainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts/rules': {
      id: '/_authenticated/alerts/rules'
      path: '/alerts/rules'
      fullPath: '/alerts/rules'
      preLoaderRoute: typeof AuthenticatedAlertsRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts/history': {
      id: '/_authenticated/alerts/history'
      path: '/alerts/history'
      fullPath: '/alerts/history'
      preLoaderRoute: typeof AuthenticatedAlertsHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts/channels': {
      id: '/_authenticated/alerts/channels'
      path: '/alerts/channels'
      fullPath: '/alerts/channels'
      preLoaderRoute: typeof AuthenticatedAlertsChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/zonemta/': {
      id: '/_authenticated/servers/zonemta/'
      path: '/servers/zonemta'
      fullPath: '/servers/zonemta/'
      preLoaderRoute: typeof AuthenticatedServersZonemtaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/zonemta/$nodeId': {
      id: '/_authenticated/servers/zonemta/$nodeId'
      path: '/servers/zonemta/$nodeId'
      fullPath: '/servers/zonemta/$nodeId'
      preLoaderRoute: typeof AuthenticatedServersZonemtaNodeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs/trace/$messageId': {
      id: '/_authenticated/logs/trace/$messageId'
      path: '/logs/trace/$messageId'
      fullPath: '/logs/trace/$messageId'
      preLoaderRoute: typeof AuthenticatedLogsTraceMessageIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAlertsChannelsRoute: typeof AuthenticatedAlertsChannelsRoute
  AuthenticatedAlertsHistoryRoute: typeof AuthenticatedAlertsHistoryRoute
  AuthenticatedAlertsRulesRoute: typeof AuthenticatedAlertsRulesRoute
  AuthenticatedDestinationsDomainRoute: typeof AuthenticatedDestinationsDomainRoute
  AuthenticatedDomainsDomainRoute: typeof AuthenticatedDomainsDomainRoute
  AuthenticatedEmailFlowPerformanceRoute: typeof AuthenticatedEmailFlowPerformanceRoute
  AuthenticatedEmailFlowQueueRoute: typeof AuthenticatedEmailFlowQueueRoute
  AuthenticatedIpReputationIpRoute: typeof AuthenticatedIpReputationIpRoute
  AuthenticatedServersNodeIdRoute: typeof AuthenticatedServersNodeIdRoute
  AuthenticatedServersComparisonRoute: typeof AuthenticatedServersComparisonRoute
  AuthenticatedServersHeatmapRoute: typeof AuthenticatedServersHeatmapRoute
  AuthenticatedSpamSecurityAuthenticationRoute: typeof AuthenticatedSpamSecurityAuthenticationRoute
  AuthenticatedSpamSecurityTlsRoute: typeof AuthenticatedSpamSecurityTlsRoute
  AuthenticatedUsersAddressRoute: typeof AuthenticatedUsersAddressRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAlertsIndexRoute: typeof AuthenticatedAlertsIndexRoute
  AuthenticatedDestinationsIndexRoute: typeof AuthenticatedDestinationsIndexRoute
  AuthenticatedDomainsIndexRoute: typeof AuthenticatedDomainsIndexRoute
  AuthenticatedEmailFlowIndexRoute: typeof AuthenticatedEmailFlowIndexRoute
  AuthenticatedIpReputationIndexRoute: typeof AuthenticatedIpReputationIndexRoute
  AuthenticatedLogsIndexRoute: typeof AuthenticatedLogsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedServersIndexRoute: typeof AuthenticatedServersIndexRoute
  AuthenticatedSpamSecurityIndexRoute: typeof AuthenticatedSpamSecurityIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedLogsTraceMessageIdRoute: typeof AuthenticatedLogsTraceMessageIdRoute
  AuthenticatedServersZonemtaNodeIdRoute: typeof AuthenticatedServersZonemtaNodeIdRoute
  AuthenticatedServersZonemtaIndexRoute: typeof AuthenticatedServersZonemtaIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAlertsChannelsRoute: AuthenticatedAlertsChannelsRoute,
  AuthenticatedAlertsHistoryRoute: AuthenticatedAlertsHistoryRoute,
  AuthenticatedAlertsRulesRoute: AuthenticatedAlertsRulesRoute,
  AuthenticatedDestinationsDomainRoute: AuthenticatedDestinationsDomainRoute,
  AuthenticatedDomainsDomainRoute: AuthenticatedDomainsDomainRoute,
  AuthenticatedEmailFlowPerformanceRoute:
    AuthenticatedEmailFlowPerformanceRoute,
  AuthenticatedEmailFlowQueueRoute: AuthenticatedEmailFlowQueueRoute,
  AuthenticatedIpReputationIpRoute: AuthenticatedIpReputationIpRoute,
  AuthenticatedServersNodeIdRoute: AuthenticatedServersNodeIdRoute,
  AuthenticatedServersComparisonRoute: AuthenticatedServersComparisonRoute,
  AuthenticatedServersHeatmapRoute: AuthenticatedServersHeatmapRoute,
  AuthenticatedSpamSecurityAuthenticationRoute:
    AuthenticatedSpamSecurityAuthenticationRoute,
  AuthenticatedSpamSecurityTlsRoute: AuthenticatedSpamSecurityTlsRoute,
  AuthenticatedUsersAddressRoute: AuthenticatedUsersAddressRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAlertsIndexRoute: AuthenticatedAlertsIndexRoute,
  AuthenticatedDestinationsIndexRoute: AuthenticatedDestinationsIndexRoute,
  AuthenticatedDomainsIndexRoute: AuthenticatedDomainsIndexRoute,
  AuthenticatedEmailFlowIndexRoute: AuthenticatedEmailFlowIndexRoute,
  AuthenticatedIpReputationIndexRoute: AuthenticatedIpReputationIndexRoute,
  AuthenticatedLogsIndexRoute: AuthenticatedLogsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedServersIndexRoute: AuthenticatedServersIndexRoute,
  AuthenticatedSpamSecurityIndexRoute: AuthenticatedSpamSecurityIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedLogsTraceMessageIdRoute: AuthenticatedLogsTraceMessageIdRoute,
  AuthenticatedServersZonemtaNodeIdRoute:
    AuthenticatedServersZonemtaNodeIdRoute,
  AuthenticatedServersZonemtaIndexRoute: AuthenticatedServersZonemtaIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
